# Generated by Django 4.1.1 on 2022-09-25 14:02

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validators.validate_file_size]),
        ),
    ]
