# Generated by Django 4.1.1 on 2022-10-02 11:17

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_category_parent_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='store/images/category', validators=[store.validators.validate_file_size]),
        ),
    ]
